===codexthefirst===
Dossiers:

Captain Salvador E. Corowitz, Recon Operations — leader of the expedition. Strong leader but prone to ‘at all costs’ philosophizing

Sergeant Yanette Gulbthri — second in command, dead shot with a laser pistol, reins in Captain C’s more extreme obsessive tendencies

Philobert Hobthan — infiltration specialist. High strung. 

Catwin Evans — a mistress of deception and diverse skulduggery. A chameleon, adapting to any situation as needed. Augmented with shape shifting technology. 

Pennsylvania Whittaker — a distant nephew of Colorado Epps. Along on what was supposed to be a simple recon mission as a favour to his father. Much less useless than his family seems to believe.



“Operation BEESTING Report SD 72830od

TO: [redacted]

As per your orders, my team and I went forward with our infiltration attempt into the area discussed in [redacted]. The stealth technology provided by our friends at Adrasteia has thus far proved highly effective, providing easy passage through the various security issues that stymied our prior forays.

As surmised, the area appears to be under the control of Miss Terri’s Sugariffic Snack Company, and thus, no imminent danger is assumed, barring one choking to death on a delicious, flavour packed Comet Cake (tm)! If you have to die, die happy! My initial assessment is that the area is merely a commercial factory taking advantage of unclaimed land permits. Nevertheless, we will continue our expedition as ordered.

Respectfully,

Captain Salvador E. Corowitz
Augmented under copyright of Finch Cybernetics, upon decease please return all recoverable DNA and pursuant parts to Finch Laboratories, 1 Garden Way, NeuTerra. Failure to adhere to these policies is punishable by a fine not to exceed 5000 credits and the immediate repossession of the responsible party’s genome and any derivatives thereof.”

You frown, shrug, and look around.
->explore


===codexthesecond===
You read the message Nibu uploads onto your 'net.

"(encrypted version)

Dear Aunt Robin,

I hope you are well. Our holiday is everything we imagined—we left the spaceport yesterday for a very sweet little cottage, a nice, home-like place, thought a little commercial. We had very little trouble on the way—it's a isolated place, so lovely and uncrowded. I find myself particularly fond of the local delicacy—a shot of some local moonshine that leaves quite a burn, followed up by a blast of something sugary sweet. I’m sure I had at least six of them last night! I’ve never seen such a party.

Anyway, give my fond regards to our grandfather, and tell him that we hope to be back soon, with plenty of stories to tell!

Your loving nephew, 

Rico"


It…does not appear to be an overly subtle cypher. Still, it might be best to pass it on to Threefra and obtain an accurate decryption.



Threefra's return message comes quickly. "No, you’re absolutely right, our bosses really should consider employing a competent…uh…translator. It’s pretty much what you think it is. At least our friends made it to the relay station, even if the message never got through. And it seems they thought everything was going quite according to plan. That’s useful information, at least. Alright, then. Back into the breach with you. And…maybe don’t ping me again til you’ve gotten something a little more interesting, eh?" ->outbuildings.choices


===codexthethird===
"This is an emergency broadcast from Minerva 1, sending to alert you of a security breach in our chain of commaTRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!TRY OUR NEW INCREDIBLE NUKE PROOF CAKE POPS, NOW LEAD FREE! COME ON AND TASTE THE APOCALYPSE!" 
->offices.back
